.PHONY: clean All

All:
	@echo "----------Building project:[ prize_draw - Debug ]----------"
	@cd "prize_draw" && "$(MAKE)" -f  "prize_draw.mk"
clean:
	@echo "----------Cleaning project:[ prize_draw - Debug ]----------"
	@cd "prize_draw" && "$(MAKE)" -f  "prize_draw.mk" clean
